#!/usr/bin/env node
/**
 * jarvis-worker.js
 * Background worker that runs periodic agent cycles and saves a brief to jarvis_files.
 * Run with: `node jarvis-worker.js` or as a background service.
 */

const INTERVAL_MS = parseInt(process.env.WORKER_INTERVAL_MS || '180000', 10) // default 3 minutes
const MAYA_BASE = process.env.MAYA_BASE_URL || 'http://localhost:3000'
const AGENTS = ['@analyst', '@developer', '@researcher', '@writer', '@ux-design-expert', '@manager']

async function callAgent(agent, task, context = '') {
  try {
    const res = await fetch(`${MAYA_BASE}/api/agent-execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ agent, task, context }),
    })
    const j = await res.json().catch(() => null)
    return { agent, ok: res.ok, status: res.status, body: j }
  } catch (e) {
    return { agent, ok: false, error: String(e) }
  }
}

async function saveBrief(path, content, projectName = 'oraculo') {
  try {
    const res = await fetch(`${MAYA_BASE}/api/maya-memory`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ tool: 'write_file', payload: { path, content, project_name: projectName } }),
    })
    return await res.json().catch(() => null)
  } catch (e) {
    return { error: String(e) }
  }
}

async function runCycle() {
  const ts = new Date().toISOString()
  console.log(`[worker] starting cycle ${ts}`)

  const task = 'Periodic brief: scan recent context and produce a concise 3-line summary and one recommended action.'

  const calls = AGENTS.map((a) => callAgent(a, task))
  const results = await Promise.all(calls)

  const lines = [`# Brief — ${ts}`, 'Generated by jarvis-worker.js', '']
  for (const r of results) {
    if (r.ok && r.body && r.body.text) {
      lines.push(`## ${r.agent}`)
      lines.push(r.body.text)
      lines.push('')
    } else if (r.ok && r.body && r.body.provider && r.body.text) {
      lines.push(`## ${r.agent} (${r.body.provider})`)
      lines.push(r.body.text)
      lines.push('')
    } else {
      lines.push(`## ${r.agent}`)
      lines.push(`(failed) ${r.error || JSON.stringify(r.body) || r.status}`)
      lines.push('')
    }
  }

  const content = lines.join('\n')
  const filename = `oraculo/brief-${ts.replace(/[:.]/g, '-')}.md`
  const saved = await saveBrief(filename, content, 'oraculo')
  console.log('[worker] saved brief', filename, saved && (saved.ok || saved.data ? 'ok' : saved.error || 'failed'))
}

async function main() {
  const once = process.argv.includes('--once')
  try {
    await runCycle()
  } catch (e) {
    console.error('[worker] cycle failed', e)
  }
  if (once) return process.exit(0)
  console.log(`[worker] scheduling next run in ${INTERVAL_MS}ms`)
  setInterval(async () => {
    try {
      await runCycle()
    } catch (e) {
      console.error('[worker] cycle failed', e)
    }
  }, INTERVAL_MS)
}

main()

